# syntax=docker/dockerfile:1
ARG RELEASE_VERSION=dev
ARG RELEASE_COMMIT=unknown
ARG RELEASE_BUILT_AT=

FROM golang:1.26.5-alpine AS build
ARG RELEASE_VERSION
ARG RELEASE_COMMIT
ARG RELEASE_BUILT_AT
RUN apk add --no-cache ca-certificates git
WORKDIR /src
COPY go.mod go.sum ./
RUN --mount=type=secret,id=github_token,required=true \
    token="$(cat /run/secrets/github_token)" && \
    git config --global url."https://x-access-token:${token}@github.com/".insteadOf "https://github.com/" && \
    GOPRIVATE=github.com/Pherlsz/Gymkhana-Core GONOSUMDB=github.com/Pherlsz/Gymkhana-Core go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags="-s -w -X github.com/Pherlsz/Gymkhana-Database/internal/platform/releaseinfo.Version=${RELEASE_VERSION} -X github.com/Pherlsz/Gymkhana-Database/internal/platform/releaseinfo.Commit=${RELEASE_COMMIT} -X github.com/Pherlsz/Gymkhana-Database/internal/platform/releaseinfo.BuiltAt=${RELEASE_BUILT_AT}" \
    -o /out/migrate ./cmd/migrate
RUN CGO_ENABLED=0 GOBIN=/out go install github.com/jackc/tern/v2@v2.4.1

FROM gcr.io/distroless/static-debian12:nonroot
ARG RELEASE_VERSION
ARG RELEASE_COMMIT
ARG RELEASE_BUILT_AT
LABEL org.opencontainers.image.title="Gymkhana Database Migrations" \
      org.opencontainers.image.version="${RELEASE_VERSION}" \
      org.opencontainers.image.revision="${RELEASE_COMMIT}" \
      org.opencontainers.image.created="${RELEASE_BUILT_AT}" \
      org.opencontainers.image.source="https://github.com/Pherlsz/Gymkhana-Database"
COPY --from=build /out/migrate /migrate
COPY --from=build /out/tern /usr/local/bin/tern
COPY database/migrations /migrations
COPY database/tern.conf /tern.conf
USER nonroot:nonroot
ENTRYPOINT ["/migrate"]
CMD ["-command", "migrate", "-migrations", "/migrations", "-config", "/tern.conf"]
