/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by TanStack Router.
// Do not edit this file directly; the Vite router plugin overwrites it from src/routes.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as CustomDataRouteImport } from "./routes/custom-data";
import { Route as GoogleFormsRouteImport } from "./routes/google-forms";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MatchingRouteImport } from "./routes/matching";
import { Route as OcrRouteImport } from "./routes/ocr";
import { Route as OperationsRouteImport } from "./routes/operations";
import { Route as ProfilesRouteImport } from "./routes/profiles";
import { Route as QueryRouteImport } from "./routes/query";
import { Route as SearchRouteImport } from "./routes/search";
import { Route as TasksRouteImport } from "./routes/tasks";

const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const CustomDataRoute = CustomDataRouteImport.update({
  id: "/custom-data",
  path: "/custom-data",
  getParentRoute: () => rootRouteImport,
} as any);
const GoogleFormsRoute = GoogleFormsRouteImport.update({
  id: "/google-forms",
  path: "/google-forms",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const MatchingRoute = MatchingRouteImport.update({
  id: "/matching",
  path: "/matching",
  getParentRoute: () => rootRouteImport,
} as any);
const OcrRoute = OcrRouteImport.update({
  id: "/ocr",
  path: "/ocr",
  getParentRoute: () => rootRouteImport,
} as any);
const OperationsRoute = OperationsRouteImport.update({
  id: "/operations",
  path: "/operations",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfilesRoute = ProfilesRouteImport.update({
  id: "/profiles",
  path: "/profiles",
  getParentRoute: () => rootRouteImport,
} as any);
const QueryRoute = QueryRouteImport.update({
  id: "/query",
  path: "/query",
  getParentRoute: () => rootRouteImport,
} as any);
const SearchRoute = SearchRouteImport.update({
  id: "/search",
  path: "/search",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/custom-data": typeof CustomDataRoute;
  "/google-forms": typeof GoogleFormsRoute;
  "/matching": typeof MatchingRoute;
  "/ocr": typeof OcrRoute;
  "/operations": typeof OperationsRoute;
  "/profiles": typeof ProfilesRoute;
  "/query": typeof QueryRoute;
  "/search": typeof SearchRoute;
  "/tasks": typeof TasksRoute;
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/chat": typeof ChatRoute;
  "/custom-data": typeof CustomDataRoute;
  "/google-forms": typeof GoogleFormsRoute;
  "/matching": typeof MatchingRoute;
  "/ocr": typeof OcrRoute;
  "/operations": typeof OperationsRoute;
  "/profiles": typeof ProfilesRoute;
  "/query": typeof QueryRoute;
  "/search": typeof SearchRoute;
  "/tasks": typeof TasksRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: keyof FileRoutesByFullPath;
  fileRoutesByTo: FileRoutesByTo;
  to: keyof FileRoutesByTo;
  id: keyof FileRoutesById;
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRoute;
  CustomDataRoute: typeof CustomDataRoute;
  GoogleFormsRoute: typeof GoogleFormsRoute;
  IndexRoute: typeof IndexRoute;
  MatchingRoute: typeof MatchingRoute;
  OcrRoute: typeof OcrRoute;
  OperationsRoute: typeof OperationsRoute;
  ProfilesRoute: typeof ProfilesRoute;
  QueryRoute: typeof QueryRoute;
  SearchRoute: typeof SearchRoute;
  TasksRoute: typeof TasksRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/custom-data": {
      id: "/custom-data";
      path: "/custom-data";
      fullPath: "/custom-data";
      preLoaderRoute: typeof CustomDataRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/google-forms": {
      id: "/google-forms";
      path: "/google-forms";
      fullPath: "/google-forms";
      preLoaderRoute: typeof GoogleFormsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/matching": {
      id: "/matching";
      path: "/matching";
      fullPath: "/matching";
      preLoaderRoute: typeof MatchingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ocr": {
      id: "/ocr";
      path: "/ocr";
      fullPath: "/ocr";
      preLoaderRoute: typeof OcrRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/operations": {
      id: "/operations";
      path: "/operations";
      fullPath: "/operations";
      preLoaderRoute: typeof OperationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profiles": {
      id: "/profiles";
      path: "/profiles";
      fullPath: "/profiles";
      preLoaderRoute: typeof ProfilesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/query": {
      id: "/query";
      path: "/query";
      fullPath: "/query";
      preLoaderRoute: typeof QueryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/search": {
      id: "/search";
      path: "/search";
      fullPath: "/search";
      preLoaderRoute: typeof SearchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  ChatRoute,
  CustomDataRoute,
  GoogleFormsRoute,
  IndexRoute,
  MatchingRoute,
  OcrRoute,
  OperationsRoute,
  ProfilesRoute,
  QueryRoute,
  SearchRoute,
  TasksRoute,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
