// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_metadata.sql

package dbgen

import (
	"context"
)

const getAppMetadata = `-- name: GetAppMetadata :one
SELECT key, value, created_at, updated_at
FROM app_metadata
WHERE key = $1
`

func (q *Queries) GetAppMetadata(ctx context.Context, key string) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, getAppMetadata, key)
	var i AppMetadatum
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAppMetadata = `-- name: SetAppMetadata :one
INSERT INTO app_metadata (key, value)
VALUES ($1, $2)
ON CONFLICT (key)
DO UPDATE SET value = EXCLUDED.value, updated_at = now()
RETURNING key, value, created_at, updated_at
`

type SetAppMetadataParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetAppMetadata(ctx context.Context, arg SetAppMetadataParams) (AppMetadatum, error) {
	row := q.db.QueryRow(ctx, setAppMetadata, arg.Key, arg.Value)
	var i AppMetadatum
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
