// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authentication.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSuperadmins = `-- name: CountActiveSuperadmins :one
SELECT count(*)
FROM app_users
WHERE active AND role = 'SUPERADMIN'
`

func (q *Queries) CountActiveSuperadmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperadmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppSession = `-- name: CreateAppSession :one
INSERT INTO app_sessions (
  id,
  user_id,
  token_hash,
  expires_at
)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
`

type CreateAppSessionParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateAppSession(ctx context.Context, arg CreateAppSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, createAppSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const createAppUser = `-- name: CreateAppUser :one
INSERT INTO app_users (
  id,
  github_user_id,
  github_login,
  display_name,
  avatar_url,
  role,
  active
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
`

type CreateAppUserParams struct {
	ID           pgtype.UUID `json:"id"`
	GithubUserID int64       `json:"github_user_id"`
	GithubLogin  string      `json:"github_login"`
	DisplayName  string      `json:"display_name"`
	AvatarUrl    *string     `json:"avatar_url"`
	Role         string      `json:"role"`
	Active       bool        `json:"active"`
}

func (q *Queries) CreateAppUser(ctx context.Context, arg CreateAppUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createAppUser,
		arg.ID,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Role,
		arg.Active,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthAuditEvent = `-- name: CreateAuthAuditEvent :one
INSERT INTO auth_audit_events (
  id,
  actor_user_id,
  subject_user_id,
  event_type,
  outcome,
  request_id,
  provider_login
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, actor_user_id, subject_user_id, event_type, outcome, request_id, provider_login, occurred_at
`

type CreateAuthAuditEventParams struct {
	ID            pgtype.UUID `json:"id"`
	ActorUserID   pgtype.UUID `json:"actor_user_id"`
	SubjectUserID pgtype.UUID `json:"subject_user_id"`
	EventType     string      `json:"event_type"`
	Outcome       string      `json:"outcome"`
	RequestID     string      `json:"request_id"`
	ProviderLogin *string     `json:"provider_login"`
}

func (q *Queries) CreateAuthAuditEvent(ctx context.Context, arg CreateAuthAuditEventParams) (AuthAuditEvent, error) {
	row := q.db.QueryRow(ctx, createAuthAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.SubjectUserID,
		arg.EventType,
		arg.Outcome,
		arg.RequestID,
		arg.ProviderLogin,
	)
	var i AuthAuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.SubjectUserID,
		&i.EventType,
		&i.Outcome,
		&i.RequestID,
		&i.ProviderLogin,
		&i.OccurredAt,
	)
	return i, err
}

const getAppSessionByTokenHash = `-- name: GetAppSessionByTokenHash :one
SELECT id, user_id, token_hash, created_at, expires_at, last_seen_at, revoked_at
FROM app_sessions
WHERE token_hash = $1
`

func (q *Queries) GetAppSessionByTokenHash(ctx context.Context, tokenHash []byte) (AppSession, error) {
	row := q.db.QueryRow(ctx, getAppSessionByTokenHash, tokenHash)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAppUserByGitHubID = `-- name: GetAppUserByGitHubID :one
SELECT id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
FROM app_users
WHERE github_user_id = $1
`

func (q *Queries) GetAppUserByGitHubID(ctx context.Context, githubUserID int64) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByGitHubID, githubUserID)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppUserByID = `-- name: GetAppUserByID :one
SELECT id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
FROM app_users
WHERE id = $1
`

func (q *Queries) GetAppUserByID(ctx context.Context, id pgtype.UUID) (AppUser, error) {
	row := q.db.QueryRow(ctx, getAppUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppUsers = `-- name: ListAppUsers :many
SELECT id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
FROM app_users
ORDER BY lower(github_login), id
LIMIT $1 OFFSET $2
`

type ListAppUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAppUsers(ctx context.Context, arg ListAppUsersParams) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listAppUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AppUser{}
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.GithubUserID,
			&i.GithubLogin,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
			&i.Active,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllAppSessionsForUser = `-- name: RevokeAllAppSessionsForUser :exec
UPDATE app_sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1
`

func (q *Queries) RevokeAllAppSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAppSessionsForUser, userID)
	return err
}

const revokeAppSession = `-- name: RevokeAppSession :exec
UPDATE app_sessions
SET revoked_at = COALESCE(revoked_at, now())
WHERE id = $1
`

func (q *Queries) RevokeAppSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAppSession, id)
	return err
}

const touchAppSession = `-- name: TouchAppSession :exec
UPDATE app_sessions
SET last_seen_at = now()
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) TouchAppSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAppSession, id)
	return err
}

const updateAppUserAccess = `-- name: UpdateAppUserAccess :one
UPDATE app_users
SET role = $2,
    active = $3,
    updated_at = now(),
    version = version + 1
WHERE id = $1
  AND version = $4
RETURNING id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
`

type UpdateAppUserAccessParams struct {
	ID      pgtype.UUID `json:"id"`
	Role    string      `json:"role"`
	Active  bool        `json:"active"`
	Version int64       `json:"version"`
}

func (q *Queries) UpdateAppUserAccess(ctx context.Context, arg UpdateAppUserAccessParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateAppUserAccess,
		arg.ID,
		arg.Role,
		arg.Active,
		arg.Version,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppUserIdentity = `-- name: UpdateAppUserIdentity :one
UPDATE app_users
SET github_login = $2,
    display_name = $3,
    avatar_url = $4,
    updated_at = now(),
    version = version + 1
WHERE id = $1
RETURNING id, github_user_id, github_login, display_name, avatar_url, role, active, version, created_at, updated_at
`

type UpdateAppUserIdentityParams struct {
	ID          pgtype.UUID `json:"id"`
	GithubLogin string      `json:"github_login"`
	DisplayName string      `json:"display_name"`
	AvatarUrl   *string     `json:"avatar_url"`
}

func (q *Queries) UpdateAppUserIdentity(ctx context.Context, arg UpdateAppUserIdentityParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateAppUserIdentity,
		arg.ID,
		arg.GithubLogin,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
