// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bill_audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordBillAuditEvent = `-- name: RecordBillAuditEvent :exec
INSERT INTO bill_audit_events (
  id, actor_user_id, bill_id, source_bill_id, bill_type_id,
  holder_profile_id, event_type, outcome, request_id
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7, $8, $9
)
`

type RecordBillAuditEventParams struct {
	ID              pgtype.UUID `json:"id"`
	ActorUserID     pgtype.UUID `json:"actor_user_id"`
	BillID          pgtype.UUID `json:"bill_id"`
	SourceBillID    pgtype.UUID `json:"source_bill_id"`
	BillTypeID      pgtype.UUID `json:"bill_type_id"`
	HolderProfileID pgtype.UUID `json:"holder_profile_id"`
	EventType       string      `json:"event_type"`
	Outcome         string      `json:"outcome"`
	RequestID       string      `json:"request_id"`
}

func (q *Queries) RecordBillAuditEvent(ctx context.Context, arg RecordBillAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordBillAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.BillID,
		arg.SourceBillID,
		arg.BillTypeID,
		arg.HolderProfileID,
		arg.EventType,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}
