// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignBillCurrentUse = `-- name: AssignBillCurrentUse :one
INSERT INTO bill_current_uses (bill_id, holder_profile_id)
SELECT bill.id, $1
FROM bills AS bill
WHERE bill.id = $2 AND bill.medium = 'PHYSICAL'
ON CONFLICT (bill_id) DO UPDATE
SET holder_profile_id = EXCLUDED.holder_profile_id, assigned_at = now()
RETURNING bill_id, holder_profile_id, assigned_at
`

type AssignBillCurrentUseParams struct {
	HolderProfileID pgtype.UUID `json:"holder_profile_id"`
	BillID          pgtype.UUID `json:"bill_id"`
}

func (q *Queries) AssignBillCurrentUse(ctx context.Context, arg AssignBillCurrentUseParams) (BillCurrentUse, error) {
	row := q.db.QueryRow(ctx, assignBillCurrentUse, arg.HolderProfileID, arg.BillID)
	var i BillCurrentUse
	err := row.Scan(&i.BillID, &i.HolderProfileID, &i.AssignedAt)
	return i, err
}

const billTypeHasBills = `-- name: BillTypeHasBills :one
SELECT EXISTS(SELECT 1 FROM bills WHERE bill_type_id = $1)
`

func (q *Queries) BillTypeHasBills(ctx context.Context, billTypeID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, billTypeHasBills, billTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBillTypes = `-- name: CountBillTypes :one
SELECT count(*)
FROM bill_types
WHERE ($1::text = '' OR lower(label) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR active = $2::boolean)
`

type CountBillTypesParams struct {
	LabelFilter  string `json:"label_filter"`
	ActiveFilter string `json:"active_filter"`
}

func (q *Queries) CountBillTypes(ctx context.Context, arg CountBillTypesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBillTypes, arg.LabelFilter, arg.ActiveFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBills = `-- name: CountBills :one
SELECT count(*)
FROM bills AS bill
LEFT JOIN bill_current_uses AS bill_current_use ON bill_current_use.bill_id = bill.id
WHERE ($1::uuid IS NULL OR bill.owner_profile_id = $1::uuid)
  AND ($2::uuid IS NULL OR bill.bill_type_id = $2::uuid)
  AND ($3::text = '' OR lower(coalesce(bill.reference_value, '')) LIKE '%' || lower($3::text) || '%')
  AND ($4::text = '' OR coalesce(bill.competence, '') = $4::text)
  AND ($5::text = '' OR bill.medium = $5::text)
  AND ($6::text = '' OR
    ($6::text = 'IN_USE' AND bill.medium = 'PHYSICAL' AND bill_current_use.bill_id IS NOT NULL) OR
    ($6::text = 'AVAILABLE' AND bill.medium = 'PHYSICAL' AND bill.idle_custody = 'ORGANIZATION' AND bill_current_use.bill_id IS NULL))
  AND ($7::uuid IS NULL OR bill_current_use.holder_profile_id = $7::uuid)
`

type CountBillsParams struct {
	OwnerProfileIDFilter  pgtype.UUID `json:"owner_profile_id_filter"`
	BillTypeIDFilter      pgtype.UUID `json:"bill_type_id_filter"`
	ReferenceFilter       string      `json:"reference_filter"`
	CompetenceFilter      string      `json:"competence_filter"`
	MediumFilter          string      `json:"medium_filter"`
	StatusFilter          string      `json:"status_filter"`
	HolderProfileIDFilter pgtype.UUID `json:"holder_profile_id_filter"`
}

func (q *Queries) CountBills(ctx context.Context, arg CountBillsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBills,
		arg.OwnerProfileIDFilter,
		arg.BillTypeIDFilter,
		arg.ReferenceFilter,
		arg.CompetenceFilter,
		arg.MediumFilter,
		arg.StatusFilter,
		arg.HolderProfileIDFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBillsByType = `-- name: CountBillsByType :many
SELECT bill.bill_type_id, count(*)::bigint AS bill_count
FROM bills AS bill
LEFT JOIN bill_current_uses AS current_use ON current_use.bill_id = bill.id
WHERE bill.medium = 'PHYSICAL'
  AND (bill.idle_custody = 'ORGANIZATION' OR current_use.bill_id IS NOT NULL)
GROUP BY bill.bill_type_id
`

type CountBillsByTypeRow struct {
	BillTypeID pgtype.UUID `json:"bill_type_id"`
	BillCount  int64       `json:"bill_count"`
}

func (q *Queries) CountBillsByType(ctx context.Context) ([]CountBillsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countBillsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountBillsByTypeRow{}
	for rows.Next() {
		var i CountBillsByTypeRow
		if err := rows.Scan(&i.BillTypeID, &i.BillCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBill = `-- name: CreateBill :one
INSERT INTO bills (
  id, owner_profile_id, bill_type_id, printed_holder_name, printed_address,
  reference_value, competence, amount, currency, notes, medium, idle_custody
)
SELECT $1, $2, bill_type.id, $3,
  $4, $5, $6,
  $7, $8, $9, $10, $11
FROM bill_types AS bill_type
WHERE bill_type.id = $12 AND bill_type.active
RETURNING id, owner_profile_id, bill_type_id, printed_holder_name, printed_address, reference_value, competence, amount, currency, notes, medium, idle_custody, version, created_at, updated_at
`

type CreateBillParams struct {
	ID                pgtype.UUID    `json:"id"`
	OwnerProfileID    pgtype.UUID    `json:"owner_profile_id"`
	PrintedHolderName *string        `json:"printed_holder_name"`
	PrintedAddress    *string        `json:"printed_address"`
	ReferenceValue    *string        `json:"reference_value"`
	Competence        *string        `json:"competence"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          *string        `json:"currency"`
	Notes             *string        `json:"notes"`
	Medium            string         `json:"medium"`
	IdleCustody       *string        `json:"idle_custody"`
	BillTypeID        pgtype.UUID    `json:"bill_type_id"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.ID,
		arg.OwnerProfileID,
		arg.PrintedHolderName,
		arg.PrintedAddress,
		arg.ReferenceValue,
		arg.Competence,
		arg.Amount,
		arg.Currency,
		arg.Notes,
		arg.Medium,
		arg.IdleCustody,
		arg.BillTypeID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.BillTypeID,
		&i.PrintedHolderName,
		&i.PrintedAddress,
		&i.ReferenceValue,
		&i.Competence,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Medium,
		&i.IdleCustody,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBillType = `-- name: CreateBillType :one
INSERT INTO bill_types (
  id, technical_key, label, active
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, technical_key, label, active, version, created_at, updated_at
`

type CreateBillTypeParams struct {
	ID           pgtype.UUID `json:"id"`
	TechnicalKey string      `json:"technical_key"`
	Label        string      `json:"label"`
	Active       bool        `json:"active"`
}

func (q *Queries) CreateBillType(ctx context.Context, arg CreateBillTypeParams) (BillType, error) {
	row := q.db.QueryRow(ctx, createBillType,
		arg.ID,
		arg.TechnicalKey,
		arg.Label,
		arg.Active,
	)
	var i BillType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :one
DELETE FROM bills WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteBillParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int64       `json:"version"`
}

func (q *Queries) DeleteBill(ctx context.Context, arg DeleteBillParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteBill, arg.ID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteBillType = `-- name: DeleteBillType :one
DELETE FROM bill_types WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteBillTypeParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int64       `json:"version"`
}

func (q *Queries) DeleteBillType(ctx context.Context, arg DeleteBillTypeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteBillType, arg.ID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const duplicateBill = `-- name: DuplicateBill :one
INSERT INTO bills (
  id, owner_profile_id, bill_type_id, printed_holder_name, printed_address,
  reference_value, competence, amount, currency, notes, medium, idle_custody
)
SELECT $1, source.owner_profile_id, source.bill_type_id, source.printed_holder_name,
  source.printed_address, source.reference_value, source.competence, source.amount,
  source.currency, source.notes, source.medium, source.idle_custody
FROM bills AS source
WHERE source.id = $2
RETURNING id, owner_profile_id, bill_type_id, printed_holder_name, printed_address, reference_value, competence, amount, currency, notes, medium, idle_custody, version, created_at, updated_at
`

type DuplicateBillParams struct {
	NewID    pgtype.UUID `json:"new_id"`
	SourceID pgtype.UUID `json:"source_id"`
}

func (q *Queries) DuplicateBill(ctx context.Context, arg DuplicateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, duplicateBill, arg.NewID, arg.SourceID)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.BillTypeID,
		&i.PrintedHolderName,
		&i.PrintedAddress,
		&i.ReferenceValue,
		&i.Competence,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Medium,
		&i.IdleCustody,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillByID = `-- name: GetBillByID :one
SELECT
  bill.id, bill.owner_profile_id, bill.bill_type_id, bill.printed_holder_name, bill.printed_address, bill.reference_value, bill.competence, bill.amount, bill.currency, bill.notes, bill.medium, bill.idle_custody, bill.version, bill.created_at, bill.updated_at,
  owner.full_name AS owner_full_name,
  bill_type.technical_key AS type_technical_key,
  bill_type.label AS type_label,
  bill_type.active AS type_active,
  bill_type.version AS type_version,
  bill_type.created_at AS type_created_at,
  bill_type.updated_at AS type_updated_at,
  bill_current_use.holder_profile_id AS current_holder_profile_id,
  holder.full_name AS current_holder_full_name,
  bill_current_use.assigned_at AS current_assigned_at
FROM bills AS bill
JOIN profiles AS owner ON owner.id = bill.owner_profile_id
JOIN bill_types AS bill_type ON bill_type.id = bill.bill_type_id
LEFT JOIN bill_current_uses AS bill_current_use ON bill_current_use.bill_id = bill.id
LEFT JOIN profiles AS holder ON holder.id = bill_current_use.holder_profile_id
WHERE bill.id = $1
`

type GetBillByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OwnerProfileID         pgtype.UUID        `json:"owner_profile_id"`
	BillTypeID             pgtype.UUID        `json:"bill_type_id"`
	PrintedHolderName      *string            `json:"printed_holder_name"`
	PrintedAddress         *string            `json:"printed_address"`
	ReferenceValue         *string            `json:"reference_value"`
	Competence             *string            `json:"competence"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               *string            `json:"currency"`
	Notes                  *string            `json:"notes"`
	Medium                 string             `json:"medium"`
	IdleCustody            *string            `json:"idle_custody"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerFullName          string             `json:"owner_full_name"`
	TypeTechnicalKey       string             `json:"type_technical_key"`
	TypeLabel              string             `json:"type_label"`
	TypeActive             bool               `json:"type_active"`
	TypeVersion            int64              `json:"type_version"`
	TypeCreatedAt          pgtype.Timestamptz `json:"type_created_at"`
	TypeUpdatedAt          pgtype.Timestamptz `json:"type_updated_at"`
	CurrentHolderProfileID pgtype.UUID        `json:"current_holder_profile_id"`
	CurrentHolderFullName  *string            `json:"current_holder_full_name"`
	CurrentAssignedAt      pgtype.Timestamptz `json:"current_assigned_at"`
}

func (q *Queries) GetBillByID(ctx context.Context, id pgtype.UUID) (GetBillByIDRow, error) {
	row := q.db.QueryRow(ctx, getBillByID, id)
	var i GetBillByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.BillTypeID,
		&i.PrintedHolderName,
		&i.PrintedAddress,
		&i.ReferenceValue,
		&i.Competence,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Medium,
		&i.IdleCustody,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerFullName,
		&i.TypeTechnicalKey,
		&i.TypeLabel,
		&i.TypeActive,
		&i.TypeVersion,
		&i.TypeCreatedAt,
		&i.TypeUpdatedAt,
		&i.CurrentHolderProfileID,
		&i.CurrentHolderFullName,
		&i.CurrentAssignedAt,
	)
	return i, err
}

const getBillCurrentUse = `-- name: GetBillCurrentUse :one
SELECT bill_id, holder_profile_id, assigned_at FROM bill_current_uses WHERE bill_id = $1
`

func (q *Queries) GetBillCurrentUse(ctx context.Context, billID pgtype.UUID) (BillCurrentUse, error) {
	row := q.db.QueryRow(ctx, getBillCurrentUse, billID)
	var i BillCurrentUse
	err := row.Scan(&i.BillID, &i.HolderProfileID, &i.AssignedAt)
	return i, err
}

const getBillTypeByID = `-- name: GetBillTypeByID :one
SELECT id, technical_key, label, active, version, created_at, updated_at FROM bill_types WHERE id = $1
`

func (q *Queries) GetBillTypeByID(ctx context.Context, id pgtype.UUID) (BillType, error) {
	row := q.db.QueryRow(ctx, getBillTypeByID, id)
	var i BillType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBillTypes = `-- name: ListBillTypes :many
SELECT id, technical_key, label, active, version, created_at, updated_at
FROM bill_types
WHERE ($1::text = '' OR lower(label) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR active = $2::boolean)
ORDER BY
  CASE WHEN $3::text = 'label' AND $4::text = 'asc' THEN lower(label) END ASC,
  CASE WHEN $3::text = 'label' AND $4::text = 'desc' THEN lower(label) END DESC,
  CASE WHEN $3::text = 'technical_key' AND $4::text = 'asc' THEN technical_key END ASC,
  CASE WHEN $3::text = 'technical_key' AND $4::text = 'desc' THEN technical_key END DESC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at END ASC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN updated_at END DESC,
  id ASC
LIMIT $6
OFFSET $5
`

type ListBillTypesParams struct {
	LabelFilter  string `json:"label_filter"`
	ActiveFilter string `json:"active_filter"`
	SortField    string `json:"sort_field"`
	SortOrder    string `json:"sort_order"`
	PageOffset   int32  `json:"page_offset"`
	PageLimit    int32  `json:"page_limit"`
}

func (q *Queries) ListBillTypes(ctx context.Context, arg ListBillTypesParams) ([]BillType, error) {
	rows, err := q.db.Query(ctx, listBillTypes,
		arg.LabelFilter,
		arg.ActiveFilter,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillType{}
	for rows.Next() {
		var i BillType
		if err := rows.Scan(
			&i.ID,
			&i.TechnicalKey,
			&i.Label,
			&i.Active,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBills = `-- name: ListBills :many
SELECT
  bill.id, bill.owner_profile_id, bill.bill_type_id, bill.printed_holder_name, bill.printed_address, bill.reference_value, bill.competence, bill.amount, bill.currency, bill.notes, bill.medium, bill.idle_custody, bill.version, bill.created_at, bill.updated_at,
  owner.full_name AS owner_full_name,
  bill_type.technical_key AS type_technical_key,
  bill_type.label AS type_label,
  bill_type.active AS type_active,
  bill_type.version AS type_version,
  bill_type.created_at AS type_created_at,
  bill_type.updated_at AS type_updated_at,
  bill_current_use.holder_profile_id AS current_holder_profile_id,
  holder.full_name AS current_holder_full_name,
  bill_current_use.assigned_at AS current_assigned_at
FROM bills AS bill
JOIN profiles AS owner ON owner.id = bill.owner_profile_id
JOIN bill_types AS bill_type ON bill_type.id = bill.bill_type_id
LEFT JOIN bill_current_uses AS bill_current_use ON bill_current_use.bill_id = bill.id
LEFT JOIN profiles AS holder ON holder.id = bill_current_use.holder_profile_id
WHERE ($1::uuid IS NULL OR bill.owner_profile_id = $1::uuid)
  AND ($2::uuid IS NULL OR bill.bill_type_id = $2::uuid)
  AND ($3::text = '' OR lower(coalesce(bill.reference_value, '')) LIKE '%' || lower($3::text) || '%')
  AND ($4::text = '' OR coalesce(bill.competence, '') = $4::text)
  AND ($5::text = '' OR bill.medium = $5::text)
  AND ($6::text = '' OR
    ($6::text = 'IN_USE' AND bill.medium = 'PHYSICAL' AND bill_current_use.bill_id IS NOT NULL) OR
    ($6::text = 'AVAILABLE' AND bill.medium = 'PHYSICAL' AND bill.idle_custody = 'ORGANIZATION' AND bill_current_use.bill_id IS NULL))
  AND ($7::uuid IS NULL OR bill_current_use.holder_profile_id = $7::uuid)
ORDER BY
  CASE WHEN $8::text = 'reference_value' AND $9::text = 'asc' THEN lower(bill.reference_value) END ASC NULLS LAST,
  CASE WHEN $8::text = 'reference_value' AND $9::text = 'desc' THEN lower(bill.reference_value) END DESC NULLS LAST,
  CASE WHEN $8::text = 'type_label' AND $9::text = 'asc' THEN lower(bill_type.label) END ASC,
  CASE WHEN $8::text = 'type_label' AND $9::text = 'desc' THEN lower(bill_type.label) END DESC,
  CASE WHEN $8::text = 'competence' AND $9::text = 'asc' THEN bill.competence END ASC NULLS LAST,
  CASE WHEN $8::text = 'competence' AND $9::text = 'desc' THEN bill.competence END DESC NULLS LAST,
  CASE WHEN $8::text = 'amount' AND $9::text = 'asc' THEN bill.amount END ASC NULLS LAST,
  CASE WHEN $8::text = 'amount' AND $9::text = 'desc' THEN bill.amount END DESC NULLS LAST,
  CASE WHEN $8::text = 'created_at' AND $9::text = 'asc' THEN bill.created_at END ASC,
  CASE WHEN $8::text = 'created_at' AND $9::text = 'desc' THEN bill.created_at END DESC,
  CASE WHEN $8::text = 'updated_at' AND $9::text = 'asc' THEN bill.updated_at END ASC,
  CASE WHEN $8::text = 'updated_at' AND $9::text = 'desc' THEN bill.updated_at END DESC,
  bill.id ASC
LIMIT $11
OFFSET $10
`

type ListBillsParams struct {
	OwnerProfileIDFilter  pgtype.UUID `json:"owner_profile_id_filter"`
	BillTypeIDFilter      pgtype.UUID `json:"bill_type_id_filter"`
	ReferenceFilter       string      `json:"reference_filter"`
	CompetenceFilter      string      `json:"competence_filter"`
	MediumFilter          string      `json:"medium_filter"`
	StatusFilter          string      `json:"status_filter"`
	HolderProfileIDFilter pgtype.UUID `json:"holder_profile_id_filter"`
	SortField             string      `json:"sort_field"`
	SortOrder             string      `json:"sort_order"`
	PageOffset            int32       `json:"page_offset"`
	PageLimit             int32       `json:"page_limit"`
}

type ListBillsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	OwnerProfileID         pgtype.UUID        `json:"owner_profile_id"`
	BillTypeID             pgtype.UUID        `json:"bill_type_id"`
	PrintedHolderName      *string            `json:"printed_holder_name"`
	PrintedAddress         *string            `json:"printed_address"`
	ReferenceValue         *string            `json:"reference_value"`
	Competence             *string            `json:"competence"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Currency               *string            `json:"currency"`
	Notes                  *string            `json:"notes"`
	Medium                 string             `json:"medium"`
	IdleCustody            *string            `json:"idle_custody"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerFullName          string             `json:"owner_full_name"`
	TypeTechnicalKey       string             `json:"type_technical_key"`
	TypeLabel              string             `json:"type_label"`
	TypeActive             bool               `json:"type_active"`
	TypeVersion            int64              `json:"type_version"`
	TypeCreatedAt          pgtype.Timestamptz `json:"type_created_at"`
	TypeUpdatedAt          pgtype.Timestamptz `json:"type_updated_at"`
	CurrentHolderProfileID pgtype.UUID        `json:"current_holder_profile_id"`
	CurrentHolderFullName  *string            `json:"current_holder_full_name"`
	CurrentAssignedAt      pgtype.Timestamptz `json:"current_assigned_at"`
}

func (q *Queries) ListBills(ctx context.Context, arg ListBillsParams) ([]ListBillsRow, error) {
	rows, err := q.db.Query(ctx, listBills,
		arg.OwnerProfileIDFilter,
		arg.BillTypeIDFilter,
		arg.ReferenceFilter,
		arg.CompetenceFilter,
		arg.MediumFilter,
		arg.StatusFilter,
		arg.HolderProfileIDFilter,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillsRow{}
	for rows.Next() {
		var i ListBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerProfileID,
			&i.BillTypeID,
			&i.PrintedHolderName,
			&i.PrintedAddress,
			&i.ReferenceValue,
			&i.Competence,
			&i.Amount,
			&i.Currency,
			&i.Notes,
			&i.Medium,
			&i.IdleCustody,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerFullName,
			&i.TypeTechnicalKey,
			&i.TypeLabel,
			&i.TypeActive,
			&i.TypeVersion,
			&i.TypeCreatedAt,
			&i.TypeUpdatedAt,
			&i.CurrentHolderProfileID,
			&i.CurrentHolderFullName,
			&i.CurrentAssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnBillCurrentUse = `-- name: ReturnBillCurrentUse :one
DELETE FROM bill_current_uses WHERE bill_id = $1 RETURNING bill_id
`

func (q *Queries) ReturnBillCurrentUse(ctx context.Context, billID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, returnBillCurrentUse, billID)
	var bill_id pgtype.UUID
	err := row.Scan(&bill_id)
	return bill_id, err
}

const updateBill = `-- name: UpdateBill :one
UPDATE bills AS bill
SET owner_profile_id = $1, bill_type_id = bill_type.id,
  printed_holder_name = $2, printed_address = $3,
  reference_value = $4, competence = $5,
  amount = $6, currency = $7, notes = $8,
  medium = $9, idle_custody = $10,
  version = bill.version + 1, updated_at = now()
FROM bill_types AS bill_type
WHERE bill.id = $11 AND bill.version = $12
  AND bill_type.id = $13 AND bill_type.active
RETURNING bill.id, bill.owner_profile_id, bill.bill_type_id, bill.printed_holder_name, bill.printed_address, bill.reference_value, bill.competence, bill.amount, bill.currency, bill.notes, bill.medium, bill.idle_custody, bill.version, bill.created_at, bill.updated_at
`

type UpdateBillParams struct {
	OwnerProfileID    pgtype.UUID    `json:"owner_profile_id"`
	PrintedHolderName *string        `json:"printed_holder_name"`
	PrintedAddress    *string        `json:"printed_address"`
	ReferenceValue    *string        `json:"reference_value"`
	Competence        *string        `json:"competence"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          *string        `json:"currency"`
	Notes             *string        `json:"notes"`
	Medium            string         `json:"medium"`
	IdleCustody       *string        `json:"idle_custody"`
	ID                pgtype.UUID    `json:"id"`
	Version           int64          `json:"version"`
	BillTypeID        pgtype.UUID    `json:"bill_type_id"`
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (Bill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.OwnerProfileID,
		arg.PrintedHolderName,
		arg.PrintedAddress,
		arg.ReferenceValue,
		arg.Competence,
		arg.Amount,
		arg.Currency,
		arg.Notes,
		arg.Medium,
		arg.IdleCustody,
		arg.ID,
		arg.Version,
		arg.BillTypeID,
	)
	var i Bill
	err := row.Scan(
		&i.ID,
		&i.OwnerProfileID,
		&i.BillTypeID,
		&i.PrintedHolderName,
		&i.PrintedAddress,
		&i.ReferenceValue,
		&i.Competence,
		&i.Amount,
		&i.Currency,
		&i.Notes,
		&i.Medium,
		&i.IdleCustody,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillType = `-- name: UpdateBillType :one
UPDATE bill_types
SET label = $1, active = $2,
  version = version + 1, updated_at = now()
WHERE id = $3 AND version = $4
RETURNING id, technical_key, label, active, version, created_at, updated_at
`

type UpdateBillTypeParams struct {
	Label   string      `json:"label"`
	Active  bool        `json:"active"`
	ID      pgtype.UUID `json:"id"`
	Version int64       `json:"version"`
}

func (q *Queries) UpdateBillType(ctx context.Context, arg UpdateBillTypeParams) (BillType, error) {
	row := q.db.QueryRow(ctx, updateBillType,
		arg.Label,
		arg.Active,
		arg.ID,
		arg.Version,
	)
	var i BillType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
