// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignDocumentCurrentUse = `-- name: AssignDocumentCurrentUse :one
INSERT INTO document_current_uses (document_id, holder_profile_id)
SELECT document.id, $1
FROM documents AS document
WHERE document.id = $2 AND document.medium = 'PHYSICAL'
ON CONFLICT (document_id) DO UPDATE
SET holder_profile_id = EXCLUDED.holder_profile_id, assigned_at = now()
RETURNING document_id, holder_profile_id, assigned_at
`

type AssignDocumentCurrentUseParams struct {
	HolderProfileID pgtype.UUID `json:"holder_profile_id"`
	DocumentID      pgtype.UUID `json:"document_id"`
}

func (q *Queries) AssignDocumentCurrentUse(ctx context.Context, arg AssignDocumentCurrentUseParams) (DocumentCurrentUse, error) {
	row := q.db.QueryRow(ctx, assignDocumentCurrentUse, arg.HolderProfileID, arg.DocumentID)
	var i DocumentCurrentUse
	err := row.Scan(&i.DocumentID, &i.HolderProfileID, &i.AssignedAt)
	return i, err
}

const countDocumentTypes = `-- name: CountDocumentTypes :one
SELECT count(*)
FROM document_types
WHERE ($1::text = '' OR lower(label) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR active = $2::boolean)
`

type CountDocumentTypesParams struct {
	LabelFilter  string `json:"label_filter"`
	ActiveFilter string `json:"active_filter"`
}

func (q *Queries) CountDocumentTypes(ctx context.Context, arg CountDocumentTypesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentTypes, arg.LabelFilter, arg.ActiveFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocuments = `-- name: CountDocuments :one
SELECT count(*)
FROM documents AS document
JOIN document_presences AS presence ON presence.id = document.presence_id
LEFT JOIN document_current_uses AS document_current_use ON document_current_use.document_id = document.id
WHERE ($1::uuid IS NULL OR presence.profile_id = $1::uuid)
  AND ($2::uuid IS NULL OR presence.document_type_id = $2::uuid)
  AND ($3::text = '' OR lower(COALESCE(presence.identifier_value, '')) LIKE '%' || lower($3::text) || '%')
  AND ($4::text = '' OR document.medium = $4::text)
  AND ($5::text = '' OR
    ($5::text = 'IN_USE' AND document.medium = 'PHYSICAL' AND document_current_use.document_id IS NOT NULL) OR
    ($5::text = 'AVAILABLE' AND document.medium = 'PHYSICAL' AND document.idle_custody = 'ORGANIZATION' AND document_current_use.document_id IS NULL))
  AND ($6::uuid IS NULL OR document_current_use.holder_profile_id = $6::uuid)
`

type CountDocumentsParams struct {
	OwnerProfileIDFilter  pgtype.UUID `json:"owner_profile_id_filter"`
	DocumentTypeIDFilter  pgtype.UUID `json:"document_type_id_filter"`
	IdentifierFilter      string      `json:"identifier_filter"`
	MediumFilter          string      `json:"medium_filter"`
	StatusFilter          string      `json:"status_filter"`
	HolderProfileIDFilter pgtype.UUID `json:"holder_profile_id_filter"`
}

func (q *Queries) CountDocuments(ctx context.Context, arg CountDocumentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments,
		arg.OwnerProfileIDFilter,
		arg.DocumentTypeIDFilter,
		arg.IdentifierFilter,
		arg.MediumFilter,
		arg.StatusFilter,
		arg.HolderProfileIDFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsByType = `-- name: CountDocumentsByType :many
SELECT presence.document_type_id, count(*)::bigint AS document_count
FROM documents AS document
JOIN document_presences AS presence ON presence.id = document.presence_id
LEFT JOIN document_current_uses AS current_use ON current_use.document_id = document.id
WHERE document.medium = 'PHYSICAL'
  AND (document.idle_custody = 'ORGANIZATION' OR current_use.document_id IS NOT NULL)
GROUP BY presence.document_type_id
`

type CountDocumentsByTypeRow struct {
	DocumentTypeID pgtype.UUID `json:"document_type_id"`
	DocumentCount  int64       `json:"document_count"`
}

func (q *Queries) CountDocumentsByType(ctx context.Context) ([]CountDocumentsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countDocumentsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDocumentsByTypeRow{}
	for rows.Next() {
		var i CountDocumentsByTypeRow
		if err := rows.Scan(&i.DocumentTypeID, &i.DocumentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countExemplarsByPresence = `-- name: CountExemplarsByPresence :one
SELECT count(*) FROM documents WHERE presence_id = $1
`

func (q *Queries) CountExemplarsByPresence(ctx context.Context, presenceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countExemplarsByPresence, presenceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
  id, presence_id, medium, idle_custody, document_date, valid_until, notes
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
RETURNING id, presence_id, medium, idle_custody, document_date, valid_until, notes, version, created_at, updated_at
`

type CreateDocumentParams struct {
	ID           pgtype.UUID `json:"id"`
	PresenceID   pgtype.UUID `json:"presence_id"`
	Medium       string      `json:"medium"`
	IdleCustody  *string     `json:"idle_custody"`
	DocumentDate pgtype.Date `json:"document_date"`
	ValidUntil   pgtype.Date `json:"valid_until"`
	Notes        *string     `json:"notes"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ID,
		arg.PresenceID,
		arg.Medium,
		arg.IdleCustody,
		arg.DocumentDate,
		arg.ValidUntil,
		arg.Notes,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PresenceID,
		&i.Medium,
		&i.IdleCustody,
		&i.DocumentDate,
		&i.ValidUntil,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDocumentType = `-- name: CreateDocumentType :one
INSERT INTO document_types (
  id, technical_key, label, active, uniqueness_policy, validation_regex, date_required
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
RETURNING id, technical_key, label, active, uniqueness_policy, validation_regex, date_required, version, created_at, updated_at
`

type CreateDocumentTypeParams struct {
	ID               pgtype.UUID `json:"id"`
	TechnicalKey     string      `json:"technical_key"`
	Label            string      `json:"label"`
	Active           bool        `json:"active"`
	UniquenessPolicy string      `json:"uniqueness_policy"`
	ValidationRegex  *string     `json:"validation_regex"`
	DateRequired     bool        `json:"date_required"`
}

func (q *Queries) CreateDocumentType(ctx context.Context, arg CreateDocumentTypeParams) (DocumentType, error) {
	row := q.db.QueryRow(ctx, createDocumentType,
		arg.ID,
		arg.TechnicalKey,
		arg.Label,
		arg.Active,
		arg.UniquenessPolicy,
		arg.ValidationRegex,
		arg.DateRequired,
	)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.UniquenessPolicy,
		&i.ValidationRegex,
		&i.DateRequired,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :one
DELETE FROM documents WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteDocumentParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int64       `json:"version"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDocument, arg.ID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteDocumentCurrentUseForDelete = `-- name: DeleteDocumentCurrentUseForDelete :exec
DELETE FROM document_current_uses WHERE document_id = $1
`

func (q *Queries) DeleteDocumentCurrentUseForDelete(ctx context.Context, documentID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocumentCurrentUseForDelete, documentID)
	return err
}

const deleteDocumentType = `-- name: DeleteDocumentType :one
DELETE FROM document_types WHERE id = $1 AND version = $2 RETURNING id
`

type DeleteDocumentTypeParams struct {
	ID      pgtype.UUID `json:"id"`
	Version int64       `json:"version"`
}

func (q *Queries) DeleteDocumentType(ctx context.Context, arg DeleteDocumentTypeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteDocumentType, arg.ID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const documentTypeHasDocuments = `-- name: DocumentTypeHasDocuments :one
SELECT EXISTS(
  SELECT 1 FROM document_presences WHERE document_type_id = $1
)
`

func (q *Queries) DocumentTypeHasDocuments(ctx context.Context, documentTypeID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, documentTypeHasDocuments, documentTypeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const duplicateDocument = `-- name: DuplicateDocument :one
INSERT INTO documents (
  id, presence_id, medium, idle_custody, document_date, valid_until, notes
)
SELECT $1, source.presence_id, source.medium, source.idle_custody,
  source.document_date, source.valid_until, source.notes
FROM documents AS source
WHERE source.id = $2
RETURNING id, presence_id, medium, idle_custody, document_date, valid_until, notes, version, created_at, updated_at
`

type DuplicateDocumentParams struct {
	NewID    pgtype.UUID `json:"new_id"`
	SourceID pgtype.UUID `json:"source_id"`
}

func (q *Queries) DuplicateDocument(ctx context.Context, arg DuplicateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, duplicateDocument, arg.NewID, arg.SourceID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PresenceID,
		&i.Medium,
		&i.IdleCustody,
		&i.DocumentDate,
		&i.ValidUntil,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT
  document.id, document.presence_id, document.medium, document.idle_custody, document.document_date, document.valid_until, document.notes, document.version, document.created_at, document.updated_at,
  presence.profile_id AS owner_profile_id,
  owner.full_name AS owner_full_name,
  presence.document_type_id,
  presence.identifier_value,
  presence.claim AS presence_claim,
  presence.uniqueness_policy,
  document_type.technical_key AS type_technical_key,
  document_type.label AS type_label,
  document_type.active AS type_active,
  document_type.validation_regex AS type_validation_regex,
  document_type.date_required AS type_date_required,
  document_type.version AS type_version,
  document_type.created_at AS type_created_at,
  document_type.updated_at AS type_updated_at,
  document_current_use.holder_profile_id AS current_holder_profile_id,
  holder.full_name AS current_holder_full_name,
  document_current_use.assigned_at AS current_assigned_at
FROM documents AS document
JOIN document_presences AS presence ON presence.id = document.presence_id
JOIN profiles AS owner ON owner.id = presence.profile_id
JOIN document_types AS document_type ON document_type.id = presence.document_type_id
LEFT JOIN document_current_uses AS document_current_use ON document_current_use.document_id = document.id
LEFT JOIN profiles AS holder ON holder.id = document_current_use.holder_profile_id
WHERE document.id = $1
`

type GetDocumentByIDRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PresenceID             pgtype.UUID        `json:"presence_id"`
	Medium                 string             `json:"medium"`
	IdleCustody            *string            `json:"idle_custody"`
	DocumentDate           pgtype.Date        `json:"document_date"`
	ValidUntil             pgtype.Date        `json:"valid_until"`
	Notes                  *string            `json:"notes"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerProfileID         pgtype.UUID        `json:"owner_profile_id"`
	OwnerFullName          string             `json:"owner_full_name"`
	DocumentTypeID         pgtype.UUID        `json:"document_type_id"`
	IdentifierValue        *string            `json:"identifier_value"`
	PresenceClaim          string             `json:"presence_claim"`
	UniquenessPolicy       string             `json:"uniqueness_policy"`
	TypeTechnicalKey       string             `json:"type_technical_key"`
	TypeLabel              string             `json:"type_label"`
	TypeActive             bool               `json:"type_active"`
	TypeValidationRegex    *string            `json:"type_validation_regex"`
	TypeDateRequired       bool               `json:"type_date_required"`
	TypeVersion            int64              `json:"type_version"`
	TypeCreatedAt          pgtype.Timestamptz `json:"type_created_at"`
	TypeUpdatedAt          pgtype.Timestamptz `json:"type_updated_at"`
	CurrentHolderProfileID pgtype.UUID        `json:"current_holder_profile_id"`
	CurrentHolderFullName  *string            `json:"current_holder_full_name"`
	CurrentAssignedAt      pgtype.Timestamptz `json:"current_assigned_at"`
}

func (q *Queries) GetDocumentByID(ctx context.Context, id pgtype.UUID) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.ID,
		&i.PresenceID,
		&i.Medium,
		&i.IdleCustody,
		&i.DocumentDate,
		&i.ValidUntil,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OwnerProfileID,
		&i.OwnerFullName,
		&i.DocumentTypeID,
		&i.IdentifierValue,
		&i.PresenceClaim,
		&i.UniquenessPolicy,
		&i.TypeTechnicalKey,
		&i.TypeLabel,
		&i.TypeActive,
		&i.TypeValidationRegex,
		&i.TypeDateRequired,
		&i.TypeVersion,
		&i.TypeCreatedAt,
		&i.TypeUpdatedAt,
		&i.CurrentHolderProfileID,
		&i.CurrentHolderFullName,
		&i.CurrentAssignedAt,
	)
	return i, err
}

const getDocumentCurrentUse = `-- name: GetDocumentCurrentUse :one
SELECT document_id, holder_profile_id, assigned_at FROM document_current_uses WHERE document_id = $1
`

func (q *Queries) GetDocumentCurrentUse(ctx context.Context, documentID pgtype.UUID) (DocumentCurrentUse, error) {
	row := q.db.QueryRow(ctx, getDocumentCurrentUse, documentID)
	var i DocumentCurrentUse
	err := row.Scan(&i.DocumentID, &i.HolderProfileID, &i.AssignedAt)
	return i, err
}

const getDocumentPresence = `-- name: GetDocumentPresence :one
SELECT id, profile_id, document_type_id, uniqueness_policy, claim, identifier_value, identifier_digits, version, created_at, updated_at FROM document_presences
WHERE profile_id = $1 AND document_type_id = $2
`

type GetDocumentPresenceParams struct {
	ProfileID      pgtype.UUID `json:"profile_id"`
	DocumentTypeID pgtype.UUID `json:"document_type_id"`
}

func (q *Queries) GetDocumentPresence(ctx context.Context, arg GetDocumentPresenceParams) (DocumentPresence, error) {
	row := q.db.QueryRow(ctx, getDocumentPresence, arg.ProfileID, arg.DocumentTypeID)
	var i DocumentPresence
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DocumentTypeID,
		&i.UniquenessPolicy,
		&i.Claim,
		&i.IdentifierValue,
		&i.IdentifierDigits,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentTypeByID = `-- name: GetDocumentTypeByID :one
SELECT id, technical_key, label, active, uniqueness_policy, validation_regex, date_required, version, created_at, updated_at FROM document_types WHERE id = $1
`

func (q *Queries) GetDocumentTypeByID(ctx context.Context, id pgtype.UUID) (DocumentType, error) {
	row := q.db.QueryRow(ctx, getDocumentTypeByID, id)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.UniquenessPolicy,
		&i.ValidationRegex,
		&i.DateRequired,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDocumentTypes = `-- name: ListDocumentTypes :many
SELECT id, technical_key, label, active, uniqueness_policy, validation_regex, date_required, version, created_at, updated_at
FROM document_types
WHERE ($1::text = '' OR lower(label) LIKE '%' || lower($1::text) || '%')
  AND ($2::text = '' OR active = $2::boolean)
ORDER BY
  CASE WHEN $3::text = 'label' AND $4::text = 'asc' THEN lower(label) END ASC,
  CASE WHEN $3::text = 'label' AND $4::text = 'desc' THEN lower(label) END DESC,
  CASE WHEN $3::text = 'technical_key' AND $4::text = 'asc' THEN technical_key END ASC,
  CASE WHEN $3::text = 'technical_key' AND $4::text = 'desc' THEN technical_key END DESC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'asc' THEN created_at END ASC,
  CASE WHEN $3::text = 'created_at' AND $4::text = 'desc' THEN created_at END DESC,
  CASE WHEN $3::text = 'updated_at' AND $4::text = 'asc' THEN updated_at END ASC,
  CASE WHEN $3::text = 'updated_at' AND $4::text = 'desc' THEN updated_at END DESC,
  id ASC
LIMIT $6
OFFSET $5
`

type ListDocumentTypesParams struct {
	LabelFilter  string `json:"label_filter"`
	ActiveFilter string `json:"active_filter"`
	SortField    string `json:"sort_field"`
	SortOrder    string `json:"sort_order"`
	PageOffset   int32  `json:"page_offset"`
	PageLimit    int32  `json:"page_limit"`
}

func (q *Queries) ListDocumentTypes(ctx context.Context, arg ListDocumentTypesParams) ([]DocumentType, error) {
	rows, err := q.db.Query(ctx, listDocumentTypes,
		arg.LabelFilter,
		arg.ActiveFilter,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentType{}
	for rows.Next() {
		var i DocumentType
		if err := rows.Scan(
			&i.ID,
			&i.TechnicalKey,
			&i.Label,
			&i.Active,
			&i.UniquenessPolicy,
			&i.ValidationRegex,
			&i.DateRequired,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT
  document.id, document.presence_id, document.medium, document.idle_custody, document.document_date, document.valid_until, document.notes, document.version, document.created_at, document.updated_at,
  presence.profile_id AS owner_profile_id,
  owner.full_name AS owner_full_name,
  presence.document_type_id,
  presence.identifier_value,
  presence.claim AS presence_claim,
  presence.uniqueness_policy,
  document_type.technical_key AS type_technical_key,
  document_type.label AS type_label,
  document_type.active AS type_active,
  document_type.validation_regex AS type_validation_regex,
  document_type.date_required AS type_date_required,
  document_type.version AS type_version,
  document_type.created_at AS type_created_at,
  document_type.updated_at AS type_updated_at,
  document_current_use.holder_profile_id AS current_holder_profile_id,
  holder.full_name AS current_holder_full_name,
  document_current_use.assigned_at AS current_assigned_at
FROM documents AS document
JOIN document_presences AS presence ON presence.id = document.presence_id
JOIN profiles AS owner ON owner.id = presence.profile_id
JOIN document_types AS document_type ON document_type.id = presence.document_type_id
LEFT JOIN document_current_uses AS document_current_use ON document_current_use.document_id = document.id
LEFT JOIN profiles AS holder ON holder.id = document_current_use.holder_profile_id
WHERE ($1::uuid IS NULL OR presence.profile_id = $1::uuid)
  AND ($2::uuid IS NULL OR presence.document_type_id = $2::uuid)
  AND ($3::text = '' OR lower(COALESCE(presence.identifier_value, '')) LIKE '%' || lower($3::text) || '%')
  AND ($4::text = '' OR document.medium = $4::text)
  AND ($5::text = '' OR
    ($5::text = 'IN_USE' AND document.medium = 'PHYSICAL' AND document_current_use.document_id IS NOT NULL) OR
    ($5::text = 'AVAILABLE' AND document.medium = 'PHYSICAL' AND document.idle_custody = 'ORGANIZATION' AND document_current_use.document_id IS NULL))
  AND ($6::uuid IS NULL OR document_current_use.holder_profile_id = $6::uuid)
ORDER BY
  CASE WHEN $7::text = 'identifier_value' AND $8::text = 'asc' THEN lower(presence.identifier_value) END ASC,
  CASE WHEN $7::text = 'identifier_value' AND $8::text = 'desc' THEN lower(presence.identifier_value) END DESC,
  CASE WHEN $7::text = 'type_label' AND $8::text = 'asc' THEN lower(document_type.label) END ASC,
  CASE WHEN $7::text = 'type_label' AND $8::text = 'desc' THEN lower(document_type.label) END DESC,
  CASE WHEN $7::text = 'document_date' AND $8::text = 'asc' THEN document.document_date END ASC NULLS LAST,
  CASE WHEN $7::text = 'document_date' AND $8::text = 'desc' THEN document.document_date END DESC NULLS LAST,
  CASE WHEN $7::text = 'created_at' AND $8::text = 'asc' THEN document.created_at END ASC,
  CASE WHEN $7::text = 'created_at' AND $8::text = 'desc' THEN document.created_at END DESC,
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'asc' THEN document.updated_at END ASC,
  CASE WHEN $7::text = 'updated_at' AND $8::text = 'desc' THEN document.updated_at END DESC,
  document.id ASC
LIMIT $10
OFFSET $9
`

type ListDocumentsParams struct {
	OwnerProfileIDFilter  pgtype.UUID `json:"owner_profile_id_filter"`
	DocumentTypeIDFilter  pgtype.UUID `json:"document_type_id_filter"`
	IdentifierFilter      string      `json:"identifier_filter"`
	MediumFilter          string      `json:"medium_filter"`
	StatusFilter          string      `json:"status_filter"`
	HolderProfileIDFilter pgtype.UUID `json:"holder_profile_id_filter"`
	SortField             string      `json:"sort_field"`
	SortOrder             string      `json:"sort_order"`
	PageOffset            int32       `json:"page_offset"`
	PageLimit             int32       `json:"page_limit"`
}

type ListDocumentsRow struct {
	ID                     pgtype.UUID        `json:"id"`
	PresenceID             pgtype.UUID        `json:"presence_id"`
	Medium                 string             `json:"medium"`
	IdleCustody            *string            `json:"idle_custody"`
	DocumentDate           pgtype.Date        `json:"document_date"`
	ValidUntil             pgtype.Date        `json:"valid_until"`
	Notes                  *string            `json:"notes"`
	Version                int64              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	OwnerProfileID         pgtype.UUID        `json:"owner_profile_id"`
	OwnerFullName          string             `json:"owner_full_name"`
	DocumentTypeID         pgtype.UUID        `json:"document_type_id"`
	IdentifierValue        *string            `json:"identifier_value"`
	PresenceClaim          string             `json:"presence_claim"`
	UniquenessPolicy       string             `json:"uniqueness_policy"`
	TypeTechnicalKey       string             `json:"type_technical_key"`
	TypeLabel              string             `json:"type_label"`
	TypeActive             bool               `json:"type_active"`
	TypeValidationRegex    *string            `json:"type_validation_regex"`
	TypeDateRequired       bool               `json:"type_date_required"`
	TypeVersion            int64              `json:"type_version"`
	TypeCreatedAt          pgtype.Timestamptz `json:"type_created_at"`
	TypeUpdatedAt          pgtype.Timestamptz `json:"type_updated_at"`
	CurrentHolderProfileID pgtype.UUID        `json:"current_holder_profile_id"`
	CurrentHolderFullName  *string            `json:"current_holder_full_name"`
	CurrentAssignedAt      pgtype.Timestamptz `json:"current_assigned_at"`
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listDocuments,
		arg.OwnerProfileIDFilter,
		arg.DocumentTypeIDFilter,
		arg.IdentifierFilter,
		arg.MediumFilter,
		arg.StatusFilter,
		arg.HolderProfileIDFilter,
		arg.SortField,
		arg.SortOrder,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsRow{}
	for rows.Next() {
		var i ListDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PresenceID,
			&i.Medium,
			&i.IdleCustody,
			&i.DocumentDate,
			&i.ValidUntil,
			&i.Notes,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OwnerProfileID,
			&i.OwnerFullName,
			&i.DocumentTypeID,
			&i.IdentifierValue,
			&i.PresenceClaim,
			&i.UniquenessPolicy,
			&i.TypeTechnicalKey,
			&i.TypeLabel,
			&i.TypeActive,
			&i.TypeValidationRegex,
			&i.TypeDateRequired,
			&i.TypeVersion,
			&i.TypeCreatedAt,
			&i.TypeUpdatedAt,
			&i.CurrentHolderProfileID,
			&i.CurrentHolderFullName,
			&i.CurrentAssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnDocumentCurrentUse = `-- name: ReturnDocumentCurrentUse :one
DELETE FROM document_current_uses WHERE document_id = $1 RETURNING document_id
`

func (q *Queries) ReturnDocumentCurrentUse(ctx context.Context, documentID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, returnDocumentCurrentUse, documentID)
	var document_id pgtype.UUID
	err := row.Scan(&document_id)
	return document_id, err
}

const updateDocument = `-- name: UpdateDocument :one
UPDATE documents
SET presence_id = $1, idle_custody = $2,
  document_date = $3, valid_until = $4,
  notes = $5, medium = $6,
  version = version + 1, updated_at = now()
WHERE id = $7 AND version = $8
RETURNING id, presence_id, medium, idle_custody, document_date, valid_until, notes, version, created_at, updated_at
`

type UpdateDocumentParams struct {
	PresenceID   pgtype.UUID `json:"presence_id"`
	IdleCustody  *string     `json:"idle_custody"`
	DocumentDate pgtype.Date `json:"document_date"`
	ValidUntil   pgtype.Date `json:"valid_until"`
	Notes        *string     `json:"notes"`
	Medium       string      `json:"medium"`
	ID           pgtype.UUID `json:"id"`
	Version      int64       `json:"version"`
}

func (q *Queries) UpdateDocument(ctx context.Context, arg UpdateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocument,
		arg.PresenceID,
		arg.IdleCustody,
		arg.DocumentDate,
		arg.ValidUntil,
		arg.Notes,
		arg.Medium,
		arg.ID,
		arg.Version,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.PresenceID,
		&i.Medium,
		&i.IdleCustody,
		&i.DocumentDate,
		&i.ValidUntil,
		&i.Notes,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentPresence = `-- name: UpdateDocumentPresence :one
UPDATE document_presences
SET claim = $1, identifier_value = $2,
  uniqueness_policy = $3,
  version = version + 1, updated_at = now()
WHERE id = $4
RETURNING id, profile_id, document_type_id, uniqueness_policy, claim, identifier_value, identifier_digits, version, created_at, updated_at
`

type UpdateDocumentPresenceParams struct {
	Claim            string      `json:"claim"`
	IdentifierValue  *string     `json:"identifier_value"`
	UniquenessPolicy string      `json:"uniqueness_policy"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDocumentPresence(ctx context.Context, arg UpdateDocumentPresenceParams) (DocumentPresence, error) {
	row := q.db.QueryRow(ctx, updateDocumentPresence,
		arg.Claim,
		arg.IdentifierValue,
		arg.UniquenessPolicy,
		arg.ID,
	)
	var i DocumentPresence
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DocumentTypeID,
		&i.UniquenessPolicy,
		&i.Claim,
		&i.IdentifierValue,
		&i.IdentifierDigits,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDocumentType = `-- name: UpdateDocumentType :one
UPDATE document_types
SET label = $1, active = $2, uniqueness_policy = $3,
  validation_regex = $4, date_required = $5,
  version = version + 1, updated_at = now()
WHERE id = $6 AND version = $7
RETURNING id, technical_key, label, active, uniqueness_policy, validation_regex, date_required, version, created_at, updated_at
`

type UpdateDocumentTypeParams struct {
	Label            string      `json:"label"`
	Active           bool        `json:"active"`
	UniquenessPolicy string      `json:"uniqueness_policy"`
	ValidationRegex  *string     `json:"validation_regex"`
	DateRequired     bool        `json:"date_required"`
	ID               pgtype.UUID `json:"id"`
	Version          int64       `json:"version"`
}

func (q *Queries) UpdateDocumentType(ctx context.Context, arg UpdateDocumentTypeParams) (DocumentType, error) {
	row := q.db.QueryRow(ctx, updateDocumentType,
		arg.Label,
		arg.Active,
		arg.UniquenessPolicy,
		arg.ValidationRegex,
		arg.DateRequired,
		arg.ID,
		arg.Version,
	)
	var i DocumentType
	err := row.Scan(
		&i.ID,
		&i.TechnicalKey,
		&i.Label,
		&i.Active,
		&i.UniquenessPolicy,
		&i.ValidationRegex,
		&i.DateRequired,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDocumentPresence = `-- name: UpsertDocumentPresence :one
INSERT INTO document_presences (
  id, profile_id, document_type_id, uniqueness_policy, claim, identifier_value
)
SELECT $1, $2, document_type.id, document_type.uniqueness_policy,
  $3, $4
FROM document_types AS document_type
WHERE document_type.id = $5
ON CONFLICT (profile_id, document_type_id) DO UPDATE
SET claim = EXCLUDED.claim,
  identifier_value = EXCLUDED.identifier_value,
  uniqueness_policy = EXCLUDED.uniqueness_policy,
  version = document_presences.version + 1,
  updated_at = now()
RETURNING id, profile_id, document_type_id, uniqueness_policy, claim, identifier_value, identifier_digits, version, created_at, updated_at
`

type UpsertDocumentPresenceParams struct {
	ID              pgtype.UUID `json:"id"`
	ProfileID       pgtype.UUID `json:"profile_id"`
	Claim           string      `json:"claim"`
	IdentifierValue *string     `json:"identifier_value"`
	DocumentTypeID  pgtype.UUID `json:"document_type_id"`
}

func (q *Queries) UpsertDocumentPresence(ctx context.Context, arg UpsertDocumentPresenceParams) (DocumentPresence, error) {
	row := q.db.QueryRow(ctx, upsertDocumentPresence,
		arg.ID,
		arg.ProfileID,
		arg.Claim,
		arg.IdentifierValue,
		arg.DocumentTypeID,
	)
	var i DocumentPresence
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.DocumentTypeID,
		&i.UniquenessPolicy,
		&i.Claim,
		&i.IdentifierValue,
		&i.IdentifierDigits,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
