// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_audit.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const recordDocumentAuditEvent = `-- name: RecordDocumentAuditEvent :exec
INSERT INTO document_audit_events (
  id, actor_user_id, document_id, source_document_id, document_type_id,
  holder_profile_id, event_type, outcome, request_id
) VALUES (
  $1, $2, $3,
  $4, $5,
  $6, $7, $8, $9
)
`

type RecordDocumentAuditEventParams struct {
	ID               pgtype.UUID `json:"id"`
	ActorUserID      pgtype.UUID `json:"actor_user_id"`
	DocumentID       pgtype.UUID `json:"document_id"`
	SourceDocumentID pgtype.UUID `json:"source_document_id"`
	DocumentTypeID   pgtype.UUID `json:"document_type_id"`
	HolderProfileID  pgtype.UUID `json:"holder_profile_id"`
	EventType        string      `json:"event_type"`
	Outcome          string      `json:"outcome"`
	RequestID        string      `json:"request_id"`
}

func (q *Queries) RecordDocumentAuditEvent(ctx context.Context, arg RecordDocumentAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordDocumentAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.DocumentID,
		arg.SourceDocumentID,
		arg.DocumentTypeID,
		arg.HolderProfileID,
		arg.EventType,
		arg.Outcome,
		arg.RequestID,
	)
	return err
}
