// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppSession struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	GithubLogin  string             `json:"github_login"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthAuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	SubjectUserID pgtype.UUID        `json:"subject_user_id"`
	EventType     string             `json:"event_type"`
	Outcome       string             `json:"outcome"`
	RequestID     string             `json:"request_id"`
	ProviderLogin *string            `json:"provider_login"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}
