// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppMetadatum struct {
	Key       string             `json:"key"`
	Value     string             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AppSession struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type AppUser struct {
	ID           pgtype.UUID        `json:"id"`
	GithubUserID int64              `json:"github_user_id"`
	GithubLogin  string             `json:"github_login"`
	DisplayName  string             `json:"display_name"`
	AvatarUrl    *string            `json:"avatar_url"`
	Role         string             `json:"role"`
	Active       bool               `json:"active"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuthAuditEvent struct {
	ID            pgtype.UUID        `json:"id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	SubjectUserID pgtype.UUID        `json:"subject_user_id"`
	EventType     string             `json:"event_type"`
	Outcome       string             `json:"outcome"`
	RequestID     string             `json:"request_id"`
	ProviderLogin *string            `json:"provider_login"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type Bill struct {
	ID                pgtype.UUID        `json:"id"`
	OwnerProfileID    pgtype.UUID        `json:"owner_profile_id"`
	BillTypeID        pgtype.UUID        `json:"bill_type_id"`
	PrintedHolderName *string            `json:"printed_holder_name"`
	PrintedAddress    *string            `json:"printed_address"`
	ReferenceValue    *string            `json:"reference_value"`
	Competence        *string            `json:"competence"`
	Amount            pgtype.Numeric     `json:"amount"`
	Currency          *string            `json:"currency"`
	Notes             *string            `json:"notes"`
	RecordState       string             `json:"record_state"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BillCurrentUse struct {
	BillID          pgtype.UUID        `json:"bill_id"`
	HolderProfileID pgtype.UUID        `json:"holder_profile_id"`
	AssignedAt      pgtype.Timestamptz `json:"assigned_at"`
}

type BillType struct {
	ID                 pgtype.UUID        `json:"id"`
	TechnicalKey       string             `json:"technical_key"`
	Label              string             `json:"label"`
	Active             bool               `json:"active"`
	SupportsCurrentUse bool               `json:"supports_current_use"`
	Version            int64              `json:"version"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID               pgtype.UUID        `json:"id"`
	OwnerProfileID   pgtype.UUID        `json:"owner_profile_id"`
	DocumentTypeID   pgtype.UUID        `json:"document_type_id"`
	IdentifierValue  string             `json:"identifier_value"`
	UniquenessPolicy string             `json:"uniqueness_policy"`
	DocumentDate     pgtype.Date        `json:"document_date"`
	Notes            *string            `json:"notes"`
	RecordState      string             `json:"record_state"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type DocumentAuditEvent struct {
	ID               pgtype.UUID        `json:"id"`
	ActorUserID      pgtype.UUID        `json:"actor_user_id"`
	DocumentID       pgtype.UUID        `json:"document_id"`
	SourceDocumentID pgtype.UUID        `json:"source_document_id"`
	DocumentTypeID   pgtype.UUID        `json:"document_type_id"`
	HolderProfileID  pgtype.UUID        `json:"holder_profile_id"`
	EventType        string             `json:"event_type"`
	Outcome          string             `json:"outcome"`
	RequestID        string             `json:"request_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
}

type DocumentCurrentUse struct {
	DocumentID      pgtype.UUID        `json:"document_id"`
	HolderProfileID pgtype.UUID        `json:"holder_profile_id"`
	AssignedAt      pgtype.Timestamptz `json:"assigned_at"`
}

type DocumentType struct {
	ID               pgtype.UUID        `json:"id"`
	TechnicalKey     string             `json:"technical_key"`
	Label            string             `json:"label"`
	Active           bool               `json:"active"`
	UniquenessPolicy string             `json:"uniqueness_policy"`
	ValidationRegex  *string            `json:"validation_regex"`
	DateRequired     bool               `json:"date_required"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Profile struct {
	ID                  pgtype.UUID        `json:"id"`
	FullName            string             `json:"full_name"`
	SocialName          *string            `json:"social_name"`
	Cpf                 *string            `json:"cpf"`
	Email               *string            `json:"email"`
	MobilePhone         *string            `json:"mobile_phone"`
	LandlinePhone       *string            `json:"landline_phone"`
	AddressStreet       *string            `json:"address_street"`
	AddressNumber       *string            `json:"address_number"`
	AddressComplement   *string            `json:"address_complement"`
	AddressNeighborhood *string            `json:"address_neighborhood"`
	AddressCity         *string            `json:"address_city"`
	AddressState        *string            `json:"address_state"`
	AddressPostalCode   *string            `json:"address_postal_code"`
	Notes               *string            `json:"notes"`
	Version             int64              `json:"version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ProfileAuditEvent struct {
	ID              pgtype.UUID        `json:"id"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	ProfileID       pgtype.UUID        `json:"profile_id"`
	SourceProfileID pgtype.UUID        `json:"source_profile_id"`
	EventType       string             `json:"event_type"`
	Outcome         string             `json:"outcome"`
	RequestID       string             `json:"request_id"`
	OccurredAt      pgtype.Timestamptz `json:"occurred_at"`
}
