#!/bin/sh
set -eu
echo "api-container boot APP_ENV=${APP_ENV:-} AUTH_ENABLED=${AUTH_ENABLED:-} DB_LEN=${#DATABASE_URL} OAUTH_ID_LEN=${#GOOGLE_OAUTH_CLIENT_ID} OAUTH_SECRET_LEN=${#GOOGLE_OAUTH_CLIENT_SECRET} REDIRECT_LEN=${#GOOGLE_OAUTH_REDIRECT_URL} APP_URL_LEN=${#AUTH_APPLICATION_URL} R2=${R2_ENABLED:-}"
exec /api
